name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PWD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ringloop/pisec-brain:$GITHUB_SHA
      
    - name: Docker Push
      run: docker push ringloop/pisec-brain:$GITHUB_SHA
      
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      env:
        COMMIT_ID: $GITHUB_SHA
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PWD }}
        port: 22
        envs: COMMIT_ID
        script: cd pisec && ./deploy-brain.sh $COMMIT_ID

